### ISSUE TITLE
A way that might help train  model faster

### ISSUE THREAD

**Issue by GustavoWang** [navjindervirdee/2048-deep-reinforcement-learning#1]
Hi,

I found in the code something strange.
In  the part "Create training dataset and Train Simultaneously",
the variable  "conv1_layer2_biases is not defined. And I found it's not trained in the training period either.  Hope it would help if you also train it.
final_parameters['conv1_layer1_biases'] = session.run(conv1_layer1_biases)
                final_parameters['conv1_layer2_biases'] = session.run(conv1_layer2_biases)
                final_parameters['conv2_layer1_biases'] = session.run(conv2_layer1_biases)
                final_parameters['conv2_layer2_biases'] = session.run(conv2_layer2_biases)

**Comment by navjindervirdee** [comment]
Hi,

I did train the conv1_layer2_biases and other biases as well but they don't provide any benefits.  So, I did not train them afterward. Thanks anyways.
